### ISSUE TITLE
bitmapOfArray renders pictures upside-down

### ISSUE THREAD

**Issue by Qqwy** [tmcdonell/gloss-accelerate#2]
When creating a 2D RPGA-array using Accelerate, and then passing this one to gloss using `Graphics.Gloss.Accelerate.Data.Picture.bitmapOfArray`, the result will be upside-down, compared to `accelerate-io`'s `Data.Array.Accelerate.IO.Codec.BMP.writeImageToBMP` (which I believe to be the correct orientation).

**Comment by tmcdonell** [comment]
Hi! Sorry for not responding sooner.

Hm, it may be that gloss or bmp is (internally) flipping the image for us already. At any rate, we should definitely make it consistent between the two. Can you send me a test case or pull request?

**Comment by Qqwy** [comment]
Yes! Let me see what I can do :-)

**Comment by tmcdonell** [comment]
For prosperity here is my test file:

```haskell
import Data.Array.Accelerate.IO.Codec.BMP
import Graphics.Gloss.Accelerate.Data.Picture
import Graphics.Gloss.Interface.Pure.Display

main :: IO ()
main = do
  r   <- readImageFromBMP "lenna512.bmp"  -- accelerate-io-bmp
  bmp <- case r of
    Left  e -> error (show e)
    Right x -> return x

  let pic = bitmapOfArray bmp True  -- gloss-accelerate

  display
    (InWindow "lena" (512, 512) (10,10))
    black
    pic
```

**Comment by Qqwy** [comment]
Thank you very much! Apologies for not getting around to helping out out.

:heart:
